package loara:dyparser@0.1.0;

interface types {
    resource section {
        constructor();
        add-field : func(key : string, val : string);
        add-section : func(name : string, sec : section);
    }
    next : func() -> option<char>;
}

interface parser {
    use types.{section};
    parse-stream : func() -> section;
}

world dyparser {
    import types;
    export parser;
}
